app/billing/views.py
from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   url_for)
from flask_login import current_user, login_required

from app import db
from app.billing.forms import CreateBillingForm
from app.models import Billing
from sqlalchemy import desc

billing = Blueprint('billing', __name__)


@billing.route('/billing/create', methods=['GET', 'POST'])
@login_required
def create():
    form = CreateBillingForm()

    if form.validate_on_submit():
        billing = Billing(title=form.title.data,
                          description=form.description.data,
                          value=form.value.data,
                          work_date=form.work_date.data,
                          user_id=current_user.get_id())

        db.session.add(billing)

        db.session.commit()

        return redirect(url_for('billing.pagination'))

    return render_template('create_billing.html', title='Create Billing', form=form)


@billing.route('/billing')
@login_required
def pagination():
    page = request.args.get('page', 1, type=int)

    billings = (Billing.query
                .filter_by(user_id=current_user.get_id())
                .order_by(desc(Billing.id))
                .paginate(page=page, per_page=5))

    return render_template('pagination_billing.html', title='Search Billing', billings=billings)


@billing.route('/billing/<int:id>', methods=['GET', 'POST'])
@login_required
def update(id):
    billing = Billing.query.get_or_404(id)

    form = CreateBillingForm()

    if form.validate_on_submit():
        billing.title = form.title.data
        billing.description = form.description.data
        billing.value = form.value.data
        billing.work_date = form.work_date.data

        db.session.commit()

        flash('Billing updated with successfully.')

        return redirect(url_for('billing.update', id=id))
    elif request.method == 'GET':
        form.title.data = billing.title
        form.description.data = billing.description
        form.value.data = billing.value
        form.work_date.data = billing.work_date

    return render_template('create_billing.html', title='Update Billing', form=form)


@billing.route('/billing/<int:id>/confirm-receive')
@login_required
def confirm_receive(id):
    billing = Billing.query.get_or_404(id)

    if current_user.get_id() != billing.user_id:
        abort(403)

    billing.confirm_receive()

    db.session.commit()

    page = request.args.get('page', 1, type=int)

    return redirect(url_for('billing.pagination', page=page))


@billing.route('/billing/<int:id>/cancel-receive')
@login_required
def cancel_receive(id):
    billing = Billing.query.get_or_404(id)

    if current_user.get_id() != billing.user_id:
        abort(403)

    billing.cancel_receive()

    db.session.commit()

    page = request.args.get('page', 1, type=int)

    return redirect(url_for('billing.pagination', page=page))

app/core/views.py
from decimal import Decimal

from flask import Blueprint, render_template
from flask_login import current_user, login_required
from sqlalchemy import func

from app import db
from app.models import Billing

core = Blueprint('core', __name__)


@core.route('/')
@login_required
def home():
    total_billing_received = (db.session
                              .query(func.sum(Billing.value).label('result'))
                              .filter(
                                  Billing.user_id == current_user.get_id(),
                                  Billing.received == True
                              )
                              .first().result) or Decimal('0.00')

    total_billing_receivable = (db.session
                                .query(func.sum(Billing.value).label('result'))
                                .filter(
                                    Billing.user_id == current_user.get_id(),
                                    Billing.received == False
                                )
                                .first().result) or Decimal('0.00')

    return render_template('home.html',
                           title='Home',
                           total_billing_received=total_billing_received,
                           total_billing_receivable=total_billing_receivable)

app/user/views.py
from flask import (Blueprint, current_app, flash, redirect, render_template,
                   url_for, request)
from flask_login import current_user, login_required, login_user, logout_user

from app import db
from app.models import User
from app.user.forms import LoginForm, RegisterForm

user = Blueprint('user', __name__)


@user.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and user.authenticate(form.password.data):
            login_user(user, remember=form.remember.data)

            next_url = request.args.get('next')

            return redirect(next_url or url_for('core.home'))

        flash('Check your email or password.')

    return render_template('login.html', title='Login', form=form)


@user.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        password_hash = User.generate_password_hash(form.password.data)

        user = User(name=form.name.data,
                    email=form.email.data,
                    password=password_hash)

        db.session.add(user)

        db.session.commit()

        user.send_welcome_message()

        return redirect(url_for('user.login'))

    return render_template('register.html', title='Register', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))

app/templates/create_billing.html
{% extends "layout.html" %}

{% block content %}
<main class="create_billing__content">
    <div class="create_billing__card">
        <form class="create_billing__form" method="POST" novalidate>
            {{ form.hidden_tag() }}

            <div class="create_billing__form_group">
                {% with has_error = form.title.errors %}

                {{ form.title.label(class="create_billing__label") }}

                {% if has_error %}
                {{ form.title(class="create_billing__input create_billing__input--error") }}
                {% for error in form.title.errors %}
                <span class="create_billing__message--error">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.title(class="create_billing__input") }}
                {% endif %}

                {% endwith %}
            </div>

            <div class="create_billing__form_group">
                {% with has_error = form.description.errors %}

                {{ form.description.label(class="create_billing__label") }}

                {% if has_error %}
                {{ form.description(class="create_billing__input create_billing__input--error") }}
                {% for error in form.description.errors %}
                <span class="create_billing__message--error">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.description(class="create_billing__input") }}
                {% endif %}

                {% endwith %}
            </div>

            <div class="create_billing__form_group">
                {% with has_error = form.value.errors %}

                {{ form.value.label(class="create_billing__label") }}

                {% if has_error %}
                {{ form.value(class="create_billing__input create_billing__input--error") }}
                {% for error in form.value.errors %}
                <span class="create_billing__message--error">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.value(class="create_billing__input") }}
                {% endif %}

                {% endwith %}
            </div>

            <div class="create_billing__form_group">
                {% with has_error = form.work_date.errors %}

                {{ form.work_date.label(class="create_billing__label") }}

                {% if has_error %}
                {{ form.work_date(class="create_billing__input create_billing__input--error") }}
                {% for error in form.work_date.errors %}
                <span class="create_billing__message--error">{{ error }}</span>
                {% endfor %}
                {% else %}
                {{ form.work_date(class="create_billing__input") }}
                {% endif %}

                {% endwith %}
            </div>

            <div class="create_billing__form_group create_billing__form_group--right">
                {{ form.submit(class="create_billing__button") }}
            </div>
        </form>
    </div>
</main>
{% endblock %}

app/templates/home.html
{% extends "layout.html" %}

{% block content %}
<main class="home__content">
    <section class="home__billing home__billing--received">
        <h2>R$ {{ total_billing_received }}</h2>
        <span>Received</span>
        <img src="{{ url_for('static', filename='wallet.svg') }}" alt="icon">
    </section>

    <section class="home__billing home__billing--receivable">
        <h2>R$ {{ total_billing_receivable }}</h2>
        <span>Receivable</span>
        <img src="{{ url_for('static', filename='wallet.svg') }}" alt="icon">
    </section>

    <section class="home__billing__line_chart"></section>
</main>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <link href="https://cdn.rawgit.com/jgthms/minireset.css/master/minireset.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" rel="stylesheet">
    {% if title %}
    <title>Finance - {{ title }}</title>
    {% else %}
    <title>Finance</title>
    {% endif %}
</head>

<body>
    {% if current_user.is_authenticated %}
    <nav class="nav">
        <span class="nav__brand">Finance</span>
        <ul>
            <li class="nav__item">
                <a href="{{ url_for('core.home') }}">Home</a>
            </li>
            <li class="nav__item">
                <a href="{{ url_for('billing.pagination') }}">Billing</a>
            </li>
            <li class="nav__item">
                <a href="{{ url_for('user.logout') }}">Logout</a>
            </li class="nav__item">
        </ul>
    </nav>
    {% else %}
    <nav class="nav">
        <span class="nav__brand">Finance</span>
        <ul>
            <li class="nav__item">
                <a href="{{ url_for('user.login') }}">Login</a>
            </li>
            <li class="nav__item">
                <a href="{{ url_for('user.register') }}">Register</a>
            </li>
        </ul>
    </nav>
    {% endif %}

    {% block content %}
    {% endblock %}

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <span>{{ message }}</span>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <script src="{{ url_for('static', filename='app.min.js') }}"></script>

    {% block scripts %}
    {% endblock %}
</body>

</html>

app/templates/login.html
{% extends "layout.html" %}

{% block content %}

<main class="content login__content">
    <form class="login__form" method="POST" novalidate>
        {{ form.hidden_tag() }}

        <div class="login__form_group">
            {% with has_error = form.email.errors %}

            {{ form.email.label(class="login__form_label") }}

            {% if has_error %}
            {{ form.email(class="login__form_input login__form_input--error") }}
            {% for error in form.email.errors %}
            <span class="login__message--error">{{ error }}</span>
            {% endfor %}
            {% else %}
            {{ form.email(class="login__form_input") }}
            {% endif %}

            {% endwith %}
        </div>

        <div class="login__form_group">
            {% with has_error = form.password.errors %}

            {{ form.password.label(class="login__form_label") }}

            {% if has_error %}
            {{ form.password(class="login__form_input login__form_input--error") }}
            {% for error in form.password.errors %}
            <span class="login__message--error">{{ error }}</span>
            {% endfor %}
            {% else %}
            {{ form.password(class="login__form_input") }}
            {% endif %}

            {% endwith %}
        </div>

        <div class="login__form_group login__form_group--inline">
            {{ form.remember.label(class="login__form_label") }}
            {{ form.remember(class="login__form_input") }}
        </div>

        <div class="login__form_group">
            {{ form.submit(class="login__form_button") }}
        </div>
    </form>
</main>

{% endblock %}

app/templates/pagination_billing.html
{% extends "layout.html" %}

{% block content %}
<main class="pagination_billing__content">

    <div class="pagination_billing__card-table">
        <header class="pagination_billing__card-header">
            <h1>Search Billing</h1>
            <a class="pagination_billing__button" href="{{ url_for('billing.create') }}">Create</a>
        </header>

        <div class="pagination_billing__card-content">
            <table class="pagination_billing__table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Value</th>
                        <th colspan="2">Received</th>
                    </tr>
                </thead>

                <tbody>
                    {% for billing in billings.items %}

                    {% with received = billing.received %}
                    <tr>
                        <td><a href="{{ url_for('billing.update', id=billing.id) }}">{{ billing.id }}</a></td>
                        <td>{{ billing.title }}</td>
                        <td>{{ billing.value }}</td>
                        <td>
                            {% if received %}
                            <span>
                                <i class="pagination_billing__action--confirm fa fa-check" aria-hidden="true"></i>
                            </span>
                            {% else %}
                            <a href="{{ url_for('billing.confirm_receive', id=billing.id, page=billings.page) }}">
                                <i class="pagination_billing__action--disabled fa fa-check" aria-hidden="true"></i>
                            </a>
                            {% endif %}
                        </td>
                        <td>
                            {% if not received %}
                            <span>
                                <i class="pagination_billing__action--cancel fa fa-times" aria-hidden="true"></i>
                            </span>
                            {% else %}
                            <a href="{{ url_for('billing.cancel_receive', id=billing.id, page=billings.page) }}">
                                <i class="pagination_billing__action--disabled fas fa-times"></i>
                            </a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endwith %}

                    {% endfor %}
                </tbody>
            </table>
        </div>

        <footer class="pagination_billing__card-footer">
            <div class="pagination_billing__pages">
                {% if billings.has_prev %}
                <a href="{{ url_for('billing.pagination', page=billings.prev_num) }}">
                    <i class="fas fa-caret-left"></i>
                </a>
                {% else %}
                <span>
                    <i class="fas fa-caret-left"></i>
                </span>
                {% endif %}

                <span>{{ billings.page }}</span>

                {% if billings.has_next %}
                <a href="{{ url_for('billing.pagination', page=billings.next_num) }}">
                    <i class="fas fa-caret-right"></i>
                </a>
                {% else %}
                <span>
                    <i class="fas fa-caret-right"></i>
                </span>
                {% endif %}
            </div>
        </footer>
    </div>

</main>
{% endblock %}

app/templates/register.html
{% extends "layout.html" %}

{% block content %}
<main class="register__content">
    <form class="register__form" method="POST" novalidate>
        {{ form.hidden_tag() }}

        <div class="register__form_group">
            {% with has_error = form.name.errors %}

            {{ form.name.label(class="register__form_label") }}

            {% if has_error %}
            {{ form.name(class="register__form_input register__form_input--error") }}
            {% for error in form.name.errors %}
            <span class="register__message--error">{{ error }}</span>
            {% endfor %}
            {% else %}
            {{ form.name(class="register__form_input") }}
            {% endif %}

            {% endwith %}
        </div>

        <div class="register__form_group">
            {% with has_error = form.email.errors %}

            {{ form.email.label(class="register__form_label") }}

            {% if has_error %}
            {{ form.email(class="register__form_input register__form_input--error") }}
            {% for error in form.email.errors %}
            <span class="register__message--error">{{ error }}</span>
            {% endfor %}
            {% else %}
            {{ form.email(class="register__form_input") }}
            {% endif %}

            {% endwith %}
        </div>

        <div class="register__form_group">
            {% with has_error = form.password.errors %}

            {{ form.password.label(class="register__form_label") }}

            {% if has_error %}
            {{ form.password(class="register__form_input register__form_input--error") }}
            {% for error in form.password.errors %}
            <span class="register__message--error">{{ error }}</span>
            {% endfor %}
            {% else %}
            {{ form.password(class="register__form_input") }}
            {% endif %}

            {% endwith %}
        </div>

        <div class="register__form_group">
            {% with has_error = form.confirm_password.errors %}

            {{ form.confirm_password.label(class="register__form_label") }}

            {% if has_error %}
            {{ form.confirm_password(class="register__form_input register__form_input--error") }}
            {% for error in form.confirm_password.errors %}
            <span class="register__message--error">{{ error }}</span>
            {% endfor %}
            {% else %}
            {{ form.confirm_password(class="register__form_input") }}
            {% endif %}

            {% endwith %}
        </div>

        <div class="register__form_group">
            {{ form.submit(class="register__form_button") }}
        </div>
    </form>
</main>
{% endblock %}